### ISSUE TITLE
generate code

### ISSUE THREAD

**Issue by JiriPrajz** [dmitry-pavlov/openapi-connected-service#37] opened 2019-08-20 12:16 UTC
Hi

After generate Generated.cs , This file had a lot of errors.  
Generator created this piece of code :

`public enum System
    {
        [System.Runtime.Serialization.EnumMember(Value = @"web")]
        Web = 0,
    }`

And e.g  [System.Runtime.Serialization.EnumMember(Value = @"web")] showed error . Runtime did not exists under type System, because System was enum type. 
When changed enum System  to e.g. System5 all errors disappeared. 
then i had to fix GetProductgroupMediaUsingGETAsync . i Changed parameter System to System5.

**Comment by dmitry-pavlov** [comment] 2019-08-20 18:44
Hi @JiriPrajz, thanks for reporting this. The problem is the naming on API side you generate the client for. Using "System" as we can see might cause naming conflicts with .NET types. It could be fixed with full namespace for "System" enum. But this should be fixed on NSwag side - the code generator used by this Visual Studio extension. Feel free to [raise an issue on NSwag](https://github.com/RicoSuter/NSwag/issues) project managed by Rico Suter.

**Closed as completed by dmitry-pavlov** 2019-08-20 18:44 UTC
